{% set version = "3.1.5" %}

package:
  name: opengis
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/28/ee/cd2866c2bac68f047fa1c2513bef14a85f01e8401e56e83cde706e2d83f1/opengis-3.1.5.tar.gz
  sha256: ee539b24675d49dfdf5d599d7217c44f6888f33381be3cdacc6db57c07c0c787

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - numpy
    - gdal
    - geopandas
    - rasterio
    - shapely
    - rasterstats

test:
  imports:
    - opengis
  commands:
    - pip check
  requires:
    - pip

about:
  summary: An open source GIS tool.
  description: |
    This is an open source GIS tool.
  dev_url: https://github.com/caaszj/opengis
  license: MIT
  license_file: LICENSE.txt

extra:
  channels:
    - conda-forge