{% set version = "3.1.4" %}

package:
  name: opengis
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d7/d4/d5e085a9b7bb3bcf76317a1af04aea2de4a9cfb90573248478fdf67eadc7/opengis-3.1.4.tar.gz
  sha256: e487ca39283580f436d5b144b190784ce8b284065c47f71d282e7c278484591e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - conda-forge::numpy
    - conda-forge::gdal
    - conda-forge::geopandas
    - conda-forge::rasterio
    - conda-forge::shapely
    - conda-forge::rasterstats

test:
  imports:
    - opengis
  commands:
    - pip check
  requires:
    - pip

about:
  summary: An open source GIS tool.
  description: |
    This is an open source GIS tool.
  dev_url: https://github.com/caaszj/opengis
  license: MIT
  license_file: LICENSE.txt

extra:
  channels:
    - conda-forge